# Site settings
title: Shoumik Palkar
tag_text: Shoumik Palkar
description: I am a second year Computer Science graduate student at Stanford University.

# Build settings
markdown: kramdown

exclude: ["README.md"]
